import json
d = json.load(open('replays/curl_42.json'))
steps = d.get('steps', [])
print(f'Total steps: {len(steps)}')
footer = d.get('footer', {})
print(f'Outcome: {footer.get("outcome")}')
print(f'Telemetry: {footer.get("telemetry")}')
print()
for s in steps[-15:]:
    t = s.get('t', 0)
    ball = s.get('ball', {})
    players = s.get('players', [])
    wr = next((p for p in players if p.get('id') == 'WR1'), {})
    cb = next((p for p in players if p.get('id') == 'CB1'), {})
    wp = wr.get('pos', [0, 0])
    cp = cb.get('pos', [0, 0])
    bstate = ball.get('state', '?')
    bpos = ball.get('pos', [0, 0, 0])
    land = ball.get('landing', [0, 0])
    eta = ball.get('eta', 0)
    print(f"t={t:.1f} WR=({wp[0]:.1f},{wp[1]:.1f}) spd={wr.get('speed',0):.1f} CB=({cp[0]:.1f},{cp[1]:.1f}) ball={bstate} bpos=({bpos[0]:.1f},{bpos[1]:.1f}) eta={eta:.2f} land=({land[0]:.1f},{land[1]:.1f})")
